apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  # Valores codificados en Base64 por seguridad (ejemplo: 'Bootcamp2026!')
  DB_PASSWORD: {{ "Qm9vdGNhbXAyMDI2IQ==" | quote }}
